import { FormEvent, useEffect, useMemo, useState } from 'react';
import { api, AdminOverview, Holding, Stock, Summary, Transaction, User } from './api';

type Page = 'overview' | 'holdings' | 'transactions' | 'catalog';
const money = (value: number | string | undefined, currency = 'INR') => new Intl.NumberFormat('en-IN', { style: 'currency', currency, maximumFractionDigits: 2 }).format(Number(value ?? 0));
const number = (value: number | string | undefined) => Number(value ?? 0).toLocaleString('en-IN', { maximumFractionDigits: 4 });

function Auth({ onLogin }: { onLogin: (user: User) => void }) {
  const [mode, setMode] = useState<'login' | 'register' | 'admin'>('login');
  const [form, setForm] = useState({ name: '', email: '', password: '', phone: '' });
  const [error, setError] = useState('');
  async function submit(event: FormEvent) {
    event.preventDefault(); setError('');
    try { const result = mode === 'register' ? await api.register(form) : mode === 'admin' ? await api.adminLogin(form) : await api.login(form); onLogin(result.user); }
    catch (err) { setError(err instanceof Error ? err.message : 'Unable to continue'); }
  }
  return <main className="auth-shell"><section className="auth-card"><div className="brand-mark">PD</div><p className="eyebrow">{mode === 'admin' ? 'ADMINISTRATOR ACCESS' : 'PERSONAL WEALTH WORKSPACE'}</p><h1>{mode === 'login' ? 'Welcome back.' : mode === 'admin' ? 'Admin sign in.' : 'Create your desk.'}</h1><p className="muted">{mode === 'admin' ? 'Review all users, portfolios, and investment activity.' : 'Track holdings, transactions, and performance in one calm view.'}</p><form onSubmit={submit}>
    {mode === 'register' && <input placeholder="Full name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} required />}
    <input type="email" placeholder="Email address" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} required />
    <input type="password" placeholder="Password" minLength={8} value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} required />
    {mode === 'register' && <input placeholder="Phone (optional)" value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} />}
    {error && <p className="error">{error}</p>}<button className="primary wide">{mode === 'login' ? 'Sign in' : mode === 'admin' ? 'Sign in as admin' : 'Create account'}</button>
  </form><button className="link-button" onClick={() => setMode(mode === 'login' ? 'register' : 'login')}>{mode === 'login' ? 'Need an account? Register' : 'Back to user sign in'}</button>{mode !== 'admin' && <button className="link-button" onClick={() => setMode('admin')}>Administrator login</button>}</section></main>;
}

function App() {
  const [user, setUser] = useState<User | null>(null);
  if (!user) return <Auth onLogin={setUser} />;
  return user.role === 'ADMIN' ? <AdminDashboard user={user} onLogout={async () => { await api.logout(); setUser(null); }} /> : <Dashboard user={user} onLogout={async () => { await api.logout(); setUser(null); }} />;
}

function AdminDashboard({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [data, setData] = useState<AdminOverview>(); const [error, setError] = useState('');
  useEffect(() => { api.adminOverview().then(setData).catch(err => setError(err.message)); }, []);
  return <div className="app-shell"><aside><div className="sidebar-brand"><span className="brand-mark small">PD</span><span>Portfolio Admin</span></div><p className="sidebar-label">ADMIN CONSOLE</p><p className="muted" style={{ padding: '0 10px', color: '#aebbd0' }}>Global read-only oversight of users, holdings, and activity.</p><div className="sidebar-bottom"><div className="user-chip"><span className="avatar">A</span><div><strong>{user.name}</strong><small>{user.email}</small></div></div><button className="nav-item" onClick={onLogout}><span>↪</span>Sign out</button></div></aside><main className="content"><header><div><p className="eyebrow">ADMINISTRATOR CONSOLE</p><h2>System overview</h2></div><span className="pill buy-pill">ADMIN</span></header>{error && <div className="notice">{error}</div>}<div className="metric-grid">{[['Registered users', data?.counts.users], ['Companies', data?.counts.companies], ['Stocks', data?.counts.stocks], ['Active portfolios', data?.counts.activePortfolios]].map(([label, value]) => <Metric key={String(label)} label={String(label)} value={String(value ?? 0)} />)}</div><div className="section-row"><section className="panel wide-panel"><div className="panel-heading"><div><p className="eyebrow">ALL USERS</p><h3>Registered accounts</h3></div></div><div className="table-wrap"><table><thead><tr><th>Name</th><th>Email</th><th>Role</th><th>Created</th></tr></thead><tbody>{data?.users.map(item => <tr key={item.id}><td>{item.name}</td><td>{item.email}</td><td><span className="pill buy-pill">{item.role}</span></td><td>{new Date(item.createdAt).toLocaleDateString('en-IN')}</td></tr>)}</tbody></table></div></section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">ALL HOLDINGS</p><h3>Portfolio positions</h3></div></div>{data?.portfolios.map((item, i) => <div className="activity-row" key={`${item.user.email}-${item.stock.symbol}-${i}`}><span className="activity-dot buy"></span><div><strong>{item.stock.symbol} · {item.user.name}</strong><small>{item.user.email}</small></div><b>{number(item.quantityHeld)} shares</b></div>)}</section></div></main></div>;
}

function Dashboard({ user, onLogout }: { user: User; onLogout: () => void }) {
  const [page, setPage] = useState<Page>('overview');
  const [holdings, setHoldings] = useState<Holding[]>([]); const [transactions, setTransactions] = useState<Transaction[]>([]); const [stocks, setStocks] = useState<Stock[]>([]); const [summary, setSummary] = useState<Summary>(); const [notice, setNotice] = useState('');
  const refresh = async () => { try { const [p, t, s, r] = await Promise.all([api.portfolio(), api.transactions(), api.stocks(), api.summary()]); setHoldings(p.portfolio); setTransactions(t.transactions); setStocks(s.stocks); setSummary(r.summary); } catch (err) { setNotice(err instanceof Error ? err.message : 'Unable to load dashboard'); } };
  useEffect(() => { refresh(); }, []);
  const nav = [{ id: 'overview', label: 'Overview', icon: '◈' }, { id: 'holdings', label: 'Holdings', icon: '▦' }, { id: 'transactions', label: 'Transactions', icon: '↕' }, { id: 'catalog', label: 'Stock catalog', icon: '⌕' }] as const;
  return <div className="app-shell"><aside><div className="sidebar-brand"><span className="brand-mark small">PD</span><span>Portfolio Desk</span></div><p className="sidebar-label">WORKSPACE</p><nav>{nav.map(item => <button key={item.id} className={page === item.id ? 'nav-item active' : 'nav-item'} onClick={() => setPage(item.id)}><span>{item.icon}</span>{item.label}</button>)}</nav><div className="sidebar-bottom"><div className="user-chip"><span className="avatar">{user.name.slice(0, 1).toUpperCase()}</span><div><strong>{user.name}</strong><small>{user.email}</small></div></div><button className="nav-item" onClick={onLogout}><span>↪</span>Sign out</button></div></aside><main className="content"><header><div><p className="eyebrow">{new Date().toLocaleDateString('en-IN', { weekday: 'long', month: 'long', day: 'numeric' })}</p><h2>{page === 'overview' ? `Good morning, ${user.name.split(' ')[0]}.` : nav.find(n => n.id === page)?.label}</h2></div><button className="outline" onClick={refresh}>Refresh data</button></header>{notice && <div className="notice">{notice}</div>}{page === 'overview' && <Overview summary={summary} holdings={holdings} transactions={transactions} onTrade={() => setPage('holdings')} />}{page === 'holdings' && <Holdings holdings={holdings} stocks={stocks} onDone={refresh} />}{page === 'transactions' && <Transactions transactions={transactions} />}{page === 'catalog' && <Catalog stocks={stocks} />}</main></div>;
}

function Overview({ summary, holdings, transactions, onTrade }: { summary?: Summary; holdings: Holding[]; transactions: Transaction[]; onTrade: () => void }) { const pnl = Number(summary?.unrealized_pnl ?? 0) + Number(summary?.realizedPnl ?? 0); return <><div className="hero-card"><div><p className="eyebrow light">TOTAL PORTFOLIO VALUE</p><h1>{money(summary?.market_value)}</h1><p className={pnl >= 0 ? 'positive' : 'negative'}>{pnl >= 0 ? '↗' : '↘'} {money(pnl)} total return</p></div><div className="hero-orbit">◌<span>2025</span></div></div><div className="metric-grid"><Metric label="Invested amount" value={money(summary?.invested_amount)} /><Metric label="Unrealized P/L" value={money(summary?.unrealized_pnl)} tone={Number(summary?.unrealized_pnl) >= 0 ? 'positive' : 'negative'} /><Metric label="Realized P/L" value={money(summary?.realizedPnl)} tone={Number(summary?.realizedPnl) >= 0 ? 'positive' : 'negative'} /><Metric label="Active positions" value={String(holdings.length)} /></div><div className="section-row"><section className="panel wide-panel"><div className="panel-heading"><div><p className="eyebrow">YOUR POSITIONS</p><h3>Current holdings</h3></div><button className="link-button" onClick={onTrade}>View all →</button></div>{holdings.slice(0, 5).map(h => <div className="holding-row" key={`${h.symbol}-${h.exchange}`}><div className="ticker">{h.symbol.slice(0, 2)}</div><div className="holding-name"><strong>{h.symbol}</strong><small>{h.company_name}</small></div><strong>{money(h.market_value, h.currency)}</strong><span className={Number(h.market_value) - Number(h.remaining_cost) >= 0 ? 'positive' : 'negative'}>{money(Number(h.market_value) - Number(h.remaining_cost), h.currency)}</span></div>)}{!holdings.length && <Empty text="Your holdings will appear here after your first buy." />}</section><section className="panel"><div className="panel-heading"><div><p className="eyebrow">LATEST ACTIVITY</p><h3>Transactions</h3></div></div>{transactions.slice(0, 4).map(t => <div className="activity-row" key={`${t.transaction_type}-${t.trade_date}-${t.symbol}`}><span className={t.transaction_type === 'BUY' ? 'activity-dot buy' : 'activity-dot sell'}></span><div><strong>{t.transaction_type === 'BUY' ? 'Bought' : 'Sold'} {t.symbol}</strong><small>{new Date(t.trade_date).toLocaleDateString('en-IN')}</small></div><b>{number(t.quantity)} shares</b></div>)}{!transactions.length && <Empty text="No transactions yet." />}</section></div></>; }
function Metric({ label, value, tone = '' }: { label: string; value: string; tone?: string }) { return <div className="metric"><p>{label}</p><strong className={tone}>{value}</strong></div>; }
function Empty({ text }: { text: string }) { return <div className="empty">{text}</div>; }

function Holdings({ holdings, stocks, onDone }: { holdings: Holding[]; stocks: Stock[]; onDone: () => void }) { const [type, setType] = useState<'buy' | 'sell'>('buy'); const [stockId, setStockId] = useState<string>(''); const [quantity, setQuantity] = useState(''); const [price, setPrice] = useState(''); const [error, setError] = useState(''); const selected = stocks.find(s => s.id === Number(stockId));
  useEffect(() => { if (!stockId && stocks[0]) { setStockId(String(stocks[0].id)); setPrice(String(stocks[0].currentPrice)); } }, [stocks, stockId]);
  async function submit(e: FormEvent) { e.preventDefault(); setError(''); try { await api.trade(type, { stockId: Number(stockId), quantity: Number(quantity), pricePerShare: Number(price) }); setQuantity(''); await onDone(); } catch (err) { setError(err instanceof Error ? err.message : 'Trade failed'); } }
  return <div className="two-column"><section className="panel"><div className="panel-heading"><div><p className="eyebrow">POSITION LEDGER</p><h3>Current holdings</h3></div></div>{holdings.length ? <div className="table-wrap"><table><thead><tr><th>Asset</th><th>Quantity</th><th>Avg. cost</th><th>Market value</th><th>P/L</th></tr></thead><tbody>{holdings.map(h => <tr key={h.symbol}><td><strong>{h.symbol}</strong><small>{h.company_name}</small></td><td>{number(h.quantity_held)}</td><td>{money(Number(h.remaining_cost) / Number(h.quantity_held), h.currency)}</td><td>{money(h.market_value, h.currency)}</td><td className={Number(h.market_value) - Number(h.remaining_cost) >= 0 ? 'positive' : 'negative'}>{money(Number(h.market_value) - Number(h.remaining_cost), h.currency)}</td></tr>)}</tbody></table></div> : <Empty text="No active holdings yet." />}</section><section className="panel trade-card"><div className="trade-tabs"><button className={type === 'buy' ? 'selected' : ''} onClick={() => setType('buy')}>Buy stock</button><button className={type === 'sell' ? 'selected' : ''} onClick={() => setType('sell')}>Sell stock</button></div><p className="eyebrow">NEW TRANSACTION</p><h3>{type === 'buy' ? 'Add to your portfolio' : 'Reduce a position'}</h3><form onSubmit={submit}><label>Stock<select value={stockId} onChange={e => { setStockId(e.target.value); const s = stocks.find(x => x.id === Number(e.target.value)); if (s) setPrice(String(s.currentPrice)); }}>{stocks.map(s => <option key={s.id} value={s.id}>{s.symbol} · {s.company.name}</option>)}</select></label><label>Quantity<input type="number" min="0.000001" step="any" value={quantity} onChange={e => setQuantity(e.target.value)} required /></label><label>Price per share<input type="number" min="0" step="0.0001" value={price} onChange={e => setPrice(e.target.value)} required /></label>{selected && <p className="helper">Latest reference price: {money(selected.currentPrice, selected.currency)}</p>}{error && <p className="error">{error}</p>}<button className="primary wide">Record {type}</button></form></section></div>; }

function Transactions({ transactions }: { transactions: Transaction[] }) { return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">AUDIT TRAIL</p><h3>Transaction history</h3></div></div><div className="table-wrap"><table><thead><tr><th>Date</th><th>Type</th><th>Asset</th><th>Quantity</th><th>Price</th><th>Value</th></tr></thead><tbody>{transactions.map((t, i) => <tr key={`${t.symbol}-${t.trade_date}-${i}`}><td>{new Date(t.trade_date).toLocaleDateString('en-IN')}</td><td><span className={t.transaction_type === 'BUY' ? 'pill buy-pill' : 'pill sell-pill'}>{t.transaction_type}</span></td><td><strong>{t.symbol}</strong><small>{t.company_name}</small></td><td>{number(t.quantity)}</td><td>{money(t.price_per_share)}</td><td>{money(Number(t.quantity) * Number(t.price_per_share))}</td></tr>)}</tbody></table>{!transactions.length && <Empty text="No transactions recorded yet." />}</div></section>; }
function Catalog({ stocks }: { stocks: Stock[] }) { const [query, setQuery] = useState(''); const results = useMemo(() => stocks.filter(s => `${s.symbol} ${s.company.name}`.toLowerCase().includes(query.toLowerCase())), [stocks, query]); return <section className="panel"><div className="panel-heading"><div><p className="eyebrow">MARKET REFERENCE</p><h3>Stock catalog</h3></div><input className="search" placeholder="Search stocks..." value={query} onChange={e => setQuery(e.target.value)} /></div><div className="catalog-grid">{results.map(s => <div className="catalog-card" key={s.id}><div className="ticker">{s.symbol.slice(0, 2)}</div><strong>{s.symbol}</strong><small>{s.company.name}</small><span>{s.exchange} · {s.currency}</span><b>{money(s.currentPrice, s.currency)}</b></div>)}</div></section>; }

export default App;
